version: '3.7'
services:
  redis:
    image: redis:7-alpine
    restart: always
  api:
    build: .
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    env_file:
      - .env
